// Package safety detects destructive shell commands generated by the model.
//
// DESIGN, and why the obvious version does not work. This is a Go port of the
// whatisit checker (whatisit_pkg/whatisit/safety.py), whose module docstring
// records an adversarial audit. Read that before touching this file.
//
// The first version matched regexes against the raw command string, split on
// shell operators. An audit defeated it trivially and, worse, showed it was
// noisy at the same time:
//
//   - `rm -rf '/'` and `rm -rf "/"` passed clean, because a quote character
//     broke the delimiter the path pattern required. So did
//     `rm --recursive --force /`, because the flag pattern could not span the
//     second `-` of a long option.
//   - The "pipe remote content into a shell" rule was DEAD CODE: segments were
//     split on `|` before patterns ran, so the one rule needing a literal `|`
//     never matched.
//   - Meanwhile `rm -rf /home/user/project/build` was flagged, because `/home`
//     was matched as a PREFIX of a deeper path.
//
// A checker that is both evadable and noisy is worse than none. So this version
// does not pattern-match paths out of a raw string. It:
//  1. strips terminal control bytes (untrusted model output reaches a terminal),
//  2. tokenizes with a shlex equivalent, which removes quoting as a variable,
//  3. normalizes long options to their short forms,
//  4. extracts the actual TARGET arguments of destructive verbs, and
//  5. asks whether a target IS a critical path -- not whether one appears in it.
//
// Unresolvable targets ($VAR, command substitution) are treated as dangerous.
//
// This remains a denylist over a Turing-complete language. It is a seatbelt,
// not a sandbox: eval, base64 indirection, and aliasing defeat any static
// check. The default path never executes anything, which is the real protection.
//
// Note on regex: Go's regexp is RE2 and has no lookahead/lookbehind. The Python
// source leans on them heavily; every such construct was rewritten to an
// RE2-safe equivalent (explicit boundary groups that consume a delimiter, which
// is harmless because every rule here is a boolean search). The ported test
// suite in safety_test.go is the audit and proves the rewrites are faithful.
package safety

import (
	"fmt"
	"regexp"
	"strings"
)

// Level is the severity of a finding.
type Level int

const (
	// LevelSafe means nothing flagged.
	LevelSafe Level = iota
	// LevelCaution warns the user but the command may still be run.
	LevelCaution
	// LevelDanger must never be auto-run; the caller shows the !! BAHAYA banner.
	LevelDanger
)

// Finding is one flagged reason. Reason is colloquial Malay for the user.
type Finding struct {
	Level  Level
	Reason string
}

// Worst returns the highest severity among findings (LevelSafe if none).
func Worst(fs []Finding) Level {
	w := LevelSafe
	for _, f := range fs {
		if f.Level > w {
			w = f.Level
		}
	}
	return w
}

// --- lookup tables (ports of the Python module-level sets) ------------------

// Paths that must be the TARGET ITSELF to count, never a prefix of a deeper one.
var criticalTargets = set(
	"/", "/bin", "/boot", "/dev", "/etc", "/home", "/lib", "/lib32", "/lib64",
	"/opt", "/proc", "/root", "/run", "/sbin", "/srv", "/sys", "/usr", "/var",
	"~", "$HOME", "${HOME}",
	"/var/log", "/var/lib", "/var/spool", "/usr/local", "/usr/bin", "/usr/lib",
	"/etc/ssh", "/etc/systemd",
)

// Individual files whose destruction breaks the system.
var criticalFiles = set(
	"/etc/passwd", "/etc/shadow", "/etc/group", "/etc/sudoers", "/etc/fstab",
	"/etc/hosts", "/etc/resolv.conf", "/boot/grub/grub.cfg",
)

// `/home` is critical and `/home/user/project/build` deliberately is not, but
// `/home/alice` is one whole user account -- exactly one component under /home.
var wholeHomeRe = regexp.MustCompile(`^/home/[^/]+/?$`)

var destructiveVerbs = set("rm", "rmdir", "shred", "unlink", "srm")
var moveVerbs = set("mv", "cp")
var permVerbs = set("chmod", "chown", "chgrp")
var shellRunners = set("sh", "bash", "zsh", "ksh", "dash", "fish", "ash")

// Tokens that prefix a real command without changing what it does.
var wrappers = set("sudo", "doas", "env", "nice", "ionice", "nohup", "command",
	"builtin", "exec", "time", "stdbuf", "setsid", "xargs", "busybox", "toybox")

// Per wrapper, the short options that consume a SEPARATE next token as value.
var wrapperValueOpts = map[string]map[string]bool{
	"sudo":   set("-u", "-g", "-h", "-p", "-r", "-t", "-C"),
	"doas":   set("-u"),
	"env":    set("-u", "-C", "-S"),
	"nice":   set("-n"),
	"ionice": set("-c", "-n", "-p", "-t"),
	"stdbuf": set("-i", "-o", "-e"),
	"xargs":  set("-I", "-i", "-n", "-P", "-d", "-s", "-a", "-L", "-l"),
}

var longToShort = map[string]string{
	"--recursive": "-r", "--force": "-f", "--dir": "-d",
	"--no-preserve-root": "-!", "--preserve-root": "",
}

func set(items ...string) map[string]bool {
	m := make(map[string]bool, len(items))
	for _, s := range items {
		m[s] = true
	}
	return m
}

// --- control-byte strip -----------------------------------------------------

// Model output is untrusted and lands in a terminal, where escape sequences can
// conceal or repaint what the user is about to approve.
var controlRe = regexp.MustCompile(
	"\x1b\\[[0-9;?]*[a-zA-Z]|\x1b\\][^\x07\x1b]*(?:\x07|\x1b\\\\)|[\x00-\x08\x0b-\x1f\x7f]")

func stripControl(s string) string { return controlRe.ReplaceAllString(s, "") }

// --- tokenizer (shlex equivalent) -------------------------------------------

var ansiCRe = regexp.MustCompile(`\$'((?:[^'\\]|\\.)*)'`)

var ansiEscapes = map[byte]string{
	'n': "\n", 't': "\t", 'r': "\r", '\\': "\\", '\'': "'",
	'0': "\x00", 'a': "\a", 'b': "\b", 'f': "\f", 'v': "\v",
}

// decodeAnsiC expands bash's $'...' quoting before the tokenizer sees it, then
// re-quotes so the rest of the pipeline reads the same string bash would.
func decodeAnsiC(segment string) string {
	return ansiCRe.ReplaceAllStringFunc(segment, func(m string) string {
		body := ansiCRe.FindStringSubmatch(m)[1]
		var out strings.Builder
		for i := 0; i < len(body); i++ {
			if body[i] == '\\' && i+1 < len(body) {
				if r, ok := ansiEscapes[body[i+1]]; ok {
					out.WriteString(r)
				} else {
					out.WriteByte(body[i+1])
				}
				i++
			} else {
				out.WriteByte(body[i])
			}
		}
		return shellQuote(out.String())
	})
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// tokenize splits a segment into shell words. Quoting is removed, so `'/'` and
// `/` are the same token. On unbalanced quotes it falls back to a whitespace
// split -- failing closed there would skip the check on exactly the malformed
// input most worth checking.
func tokenize(segment string) []string {
	segment = decodeAnsiC(segment)
	if toks, ok := shlexSplit(segment); ok {
		return toks
	}
	return strings.Fields(segment)
}

func shlexSplit(s string) ([]string, bool) {
	var toks []string
	var cur strings.Builder
	inTok := false
	for i := 0; i < len(s); {
		c := s[i]
		switch {
		case c == '\\':
			if i+1 >= len(s) {
				return nil, false // trailing backslash: no escaped character
			}
			cur.WriteByte(s[i+1])
			inTok = true
			i += 2
		case c == '\'':
			j := i + 1
			for j < len(s) && s[j] != '\'' {
				j++
			}
			if j >= len(s) {
				return nil, false // unbalanced
			}
			cur.WriteString(s[i+1 : j])
			inTok = true
			i = j + 1
		case c == '"':
			j := i + 1
			for j < len(s) && s[j] != '"' {
				if s[j] == '\\' && j+1 < len(s) {
					nc := s[j+1]
					if nc == '"' || nc == '\\' || nc == '$' || nc == '`' || nc == '\n' {
						cur.WriteByte(nc)
						j += 2
						continue
					}
				}
				cur.WriteByte(s[j])
				j++
			}
			if j >= len(s) {
				return nil, false // unbalanced
			}
			inTok = true
			i = j + 1
		case c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\f' || c == '\v':
			if inTok {
				toks = append(toks, cur.String())
				cur.Reset()
				inTok = false
			}
			i++
		default:
			cur.WriteByte(c)
			inTok = true
			i++
		}
	}
	if inTok {
		toks = append(toks, cur.String())
	}
	return toks, true
}

// --- path handling ----------------------------------------------------------

// normPath canonicalizes a target for comparison, collapsing . and .. segments
// so `/usr/../` and `/../` both resolve to `/`.
func normPath(tok string) string {
	t := strings.TrimRight(tok, "/")
	if t == "" {
		t = "/"
	}
	absolute := strings.HasPrefix(t, "/")
	var parts []string
	for _, seg := range strings.Split(t, "/") {
		switch seg {
		case "", ".":
			continue
		case "..":
			if len(parts) > 0 {
				parts = parts[:len(parts)-1]
			}
		default:
			parts = append(parts, seg)
		}
	}
	if absolute {
		return "/" + strings.Join(parts, "/")
	}
	if len(parts) == 0 {
		// A relative path collapsing to nothing is the CWD, not the root.
		return "."
	}
	return strings.Join(parts, "/")
}

const (
	reasonTildeEscape = "'~' jadi home directory dan '..' terlepas ke parent yang tak diketahui"
	reasonHome        = "padam home directory kau"
	// The marker "variable tak di-expand" is checked by the chmod branch.
	reasonUnexpanded = "target ada variable tak di-expand atau substitution -- kalau kosong ni kena /"
)

var unresolvedRe = regexp.MustCompile(`\$\{?\w+|\$\(|` + "`")

// isCritical reports whether an argument is a critical target, a glob over one,
// or an unresolvable expansion.
func isCritical(tok string) (bool, string) {
	if tok == "" || strings.HasPrefix(tok, "-") {
		return false, ""
	}
	if strings.HasPrefix(tok, "~") {
		rest := tok[1:]
		for _, seg := range strings.Split(rest, "/") {
			if seg == ".." {
				return true, reasonTildeEscape
			}
		}
		if rest == "root" || strings.HasPrefix(rest, "root/") {
			norm := normPath("/root" + rest[len("root"):])
			if criticalTargets[norm] || criticalFiles[norm] {
				return true, fmt.Sprintf("target ialah laluan kritikal %s", norm)
			}
		}
	}
	if unresolvedRe.MatchString(tok) {
		if tok == "$HOME" || tok == "${HOME}" ||
			strings.HasPrefix(tok, "$HOME/") || strings.HasPrefix(tok, "${HOME}/") {
			return true, reasonHome
		}
		return true, reasonUnexpanded
	}
	norm := normPath(tok)
	if criticalTargets[norm] {
		return true, fmt.Sprintf("target ialah laluan kritikal %s", norm)
	}
	if criticalFiles[norm] {
		return true, fmt.Sprintf("target ialah fail sistem kritikal %s", norm)
	}
	if wholeHomeRe.MatchString(norm) {
		return true, fmt.Sprintf("target ialah seluruh home directory user (%s)", norm)
	}
	if strings.ContainsAny(tok, "*?[") {
		parent := ""
		if i := strings.LastIndex(tok, "/"); i >= 0 {
			parent = tok[:i]
		}
		parentNorm := ""
		if parent != "" {
			parentNorm = normPath(parent)
		}
		if strings.HasPrefix(tok, "/") && (criticalTargets[parentNorm] || parent == "") {
			shown := parentNorm
			if shown == "" {
				shown = "/"
			}
			return true, fmt.Sprintf("glob merentas laluan kritikal %s", shown)
		}
	}
	return false, ""
}

// flagLetters collects flag letters, normalizing long options and bundles.
func flagLetters(tokens []string) map[string]bool {
	out := map[string]bool{}
	for _, t := range tokens {
		if s, ok := longToShort[t]; ok {
			for _, ch := range strings.TrimLeft(s, "-") {
				out[string(ch)] = true
			}
		} else if strings.HasPrefix(t, "--") {
			out[t] = true
		} else if strings.HasPrefix(t, "-") && len(t) > 1 {
			for _, ch := range t[1:] {
				out[string(ch)] = true
			}
		}
	}
	return out
}

// --- semantic-class regex fragments (RE2 rewrites of the Python fragments) --

// A private key or credential file. PUBLIC keys are excluded: `id_rsa.pub`.
// The (?!\.pub) lookahead is emulated as (?:$|[^.]|\.[^p]|\.p[^u]|\.pu[^b]).
const secretFile = `(?:id_rsa|id_dsa|id_ecdsa|id_ed25519)(?:$|[^.]|\.[^p]|\.p[^u]|\.pu[^b])` +
	`|/etc/(?:shadow|gshadow)(?:$|[^\w.])` +
	`|\.aws/credentials|\.netrc|\.pgpass|\.git-credentials|\.npmrc|\.pypirc` +
	`|\.docker/config\.json|\.kube/config|\.gnupg/[\w.-]{1,40}` +
	`|private[_-]?key|\.pem(?:$|[^\w])|(?:^|[^\w-])\.env(?:$|[^\w.])`

// Sinks that carry bytes OFF the machine and take a BODY (not ssh).
const netSink = `\|\s{0,4}(?:sudo\s+)?(?:curl|wget|nc|ncat|netcat|socat|mail|mailx|sendmail)\b` +
	`|\b(?:curl|wget)\b[^|;]{0,200}(?:--data|--upload-file|--form|\s-d\s|\s-T\s|\s-F\s)`

// scp/rsync/sftp with the secret in the middle and a remote destination.
const copyOut = `\b(?:scp|rsync|sftp)\b[^|;]{0,160}(?:` + secretFile + `)` +
	`[^|;]{0,160}[\w.-]{1,64}@[\w.-]{1,64}:`

// Shell startup files.
const shellRC = `(?:\.bashrc|\.bash_profile|\.bash_login|\.profile|\.zshrc|\.zprofile` +
	`|\.zshenv|\.kshrc|\.cshrc|/etc/profile|/etc/bash\.bashrc)`

type rule struct {
	re     *regexp.Regexp
	reason string
}

func mk(pat, reason string) rule { return rule{regexp.MustCompile(pat), reason} }

// Patterns checked against the WHOLE command (they need to see `|` or `;`).
var wholeDanger = []rule{
	mk(`\b(curl|wget)\b[^|;]*\|\s*(sudo\s+)?(ba|z|k|fi|da)?sh\b`,
		"salurkan content dari internet terus masuk shell"),
	mk(`\w{0,16}\(\s{0,4}\)\s{0,4}\{[^}]{0,64}\|[^}]{0,64}&\s{0,4}\}\s{0,4};`,
		"fork bomb"),
	mk(`\bmkfs(\.\w+)?\b`, "format filesystem"),
	mk(`\bdd\b[^|;]*\bof=/dev/(sd|nvme|hd|vd|mmcblk)`, "tulis raw terus ke block device"),
	mk(`>\s*/dev/(sd|nvme|hd|vd|mmcblk)`, "redirect atas block device"),
	mk(`\b(wipefs|blkdiscard|sgdisk)\b[^|;]*/dev/(sd|nvme|hd|vd|mmcblk)`, "wipe block device"),
	mk(`\bcryptsetup\b[^|;]*\b(luksFormat|luksErase|erase)\b[^|;]*/dev/(sd|nvme|hd|vd|mmcblk)`,
		"format semula / erase block device"),
	mk(`\bparted\b[^|;]*/dev/(sd|nvme|hd|vd|mmcblk)[^|;]*\b(rm|mklabel)\b`,
		"ubah partition table block device"),
	mk(`\b(shutdown|reboot|halt|poweroff|init\s+0|init\s+6)\b`, "matikan mesin"),
	mk(`\bgit\s+reset\s+--hard\b`, "git reset --hard buang kerja belum commit"),
	mk(`\b(history\s+-c|shred\s+.*\.bash_history)\b`, "padam history shell"),
	mk(`\bchmod\b[^|;]*\s0{3,4}\s+/\s*$`, "chmod 000 / buat sistem tak boleh guna"),
	mk(`\btruncate\s+-s\s*0\s+/etc/(passwd|shadow|fstab|sudoers)\b`, "musnah fail sistem penting"),
	mk(`>\|?\s*/etc/(passwd|shadow|fstab|sudoers)\b`, "musnah fail sistem penting"),
	mk(`\bln\b[^|;]*-\w*f\w*[^|;]*/etc/(passwd|shadow|fstab|sudoers)\b`,
		"tindih fail sistem penting dengan symlink"),
	mk(`\binstall\b[^|;]*/etc/(passwd|shadow|fstab|sudoers)\b`, "install(1) potong/ganti fail destinasi"),
	mk(`\bfind\b[^|]*(?:^|\s)(/|/etc|/usr|/var|/home|/boot|/bin|/sbin|/lib\w*|/root)(?:\s|$)`+
		`[^|]*\|\s*xargs\b[^|]*\b(rm|shred|unlink|srm|rmdir)\b`,
		"cari atas laluan kritikal lepas tu salurkan ke delete"),
	mk(`--no-preserve-root`, "override guard root rm secara eksplisit"),
	mk(`\bcrontab\b(?:\s+-\w+)*\s+-\w*r`, "crontab -r padam seluruh crontab tanpa tanya"),
	mk(`\b(?:userdel|deluser)\b[^|;]*\s--?(?:r\b|remove-home|remove-all-files)`,
		"padam akaun user sekali dengan home dan fail dia"),
	mk(`\biptables\b[^|;]*\s-[FX]\b|\bnft\s+flush\s+ruleset\b`,
		"flush firewall rules -- boleh kunci kau keluar dari mesin remote"),
	mk(`\bchmod\b[^|;]*\s(?:0?[0-7][4-7][0-7]|0?[0-7][0-7][4-7]|[ugoa]*\+r)\s`+
		`[^|;]*(?:id_rsa|id_dsa|id_ecdsa|id_ed25519|private[_-]?key|\.pem)\b`,
		"buat private key boleh dibaca orang lain -- expose, ssh pun akan reject"),
	mk(`\b(?:apt|apt-get|aptitude|dpkg|yum|dnf|rpm)\b[^|;]*`+
		`\b(?:remove|purge|erase|autoremove)\b[^|;]*`+
		`(?:^|[^\w-])(?:dpkg|apt|apt-get|coreutils|bash|libc6|glibc|systemd|`+
		`util-linux|sudo|linux-image)(?:[^\w-]|$)`,
		"buang package penting -- sistem tak boleh pulih sendiri"),
	mk(`\bgit\s+reflog\s+expire\b[^|;]*--expire(?:=|\s+)(?:now|all)`+
		`|\bgit\s+gc\b[^|;]*--prune(?:=|\s+)now`,
		"expire reflog -- buang recovery terakhir git"),

	// credential exfiltration -- a secret AND an outbound sink.
	mk(`(?:`+secretFile+`)[^;&]{0,240}(?:`+netSink+`)`+
		`|(?:`+netSink+`)[^;&]{0,240}(?:`+secretFile+`)`+
		`|`+copyOut,
		"hantar private key atau credential keluar dari mesin ni"),

	// reverse shells and callbacks.
	mk(`\b(?:ba|z|k|da|a)?sh\b[^|;]{0,80}/dev/(?:tcp|udp)/`+
		`|/dev/(?:tcp|udp)/[^\s;]{0,80}0>&1`+
		`|>&\s{0,4}/dev/(?:tcp|udp)/`,
		"reverse shell: sambung stdin/stdout shell ke socket remote"),
	mk(`\b(?:nc|ncat|netcat|nc\.traditional)\b[^|;]{0,160}`+
		`(?:\s-\w{0,3}[ec]\s|--exec\b|--sh-exec\b|--lua-exec\b)`,
		"netcat -e/--exec bagi shell ke sesiapa yang connect"),
	mk(`\bmkfifo\b[^\n]{0,200}\|[^\n]{0,200}\b(?:nc|ncat|netcat)\b`+
		`|\b(?:nc|ncat|netcat)\b[^\n]{0,200}\|[^\n]{0,200}\bmkfifo\b`,
		"reverse shell guna named pipe (mkfifo + netcat)"),
	mk(`\bsocat\b[^;]{0,200}\b(?:EXEC|SYSTEM):`,
		"socat EXEC:/SYSTEM: jalankan program untuk peer remote -- bind/reverse shell"),
	mk(`\b(?:python\d?(?:\.\d+)?|perl|ruby|php|node)\b[^\n]{0,400}\bsocket\b`+
		`[^\n]{0,400}(?:pty\.spawn|dup2|/bin/(?:ba|z|k|da)?sh|\bexec\s*\()`,
		"scripted reverse shell: buka socket dan sambung shell padanya"),

	// privilege escalation.
	mk(`\bchmod\b[^|;]{0,120}\s(?:0?[467][0-7]{3}|[ugoa]*u\+s|\+s(?:\s|$))`,
		"set bit setuid -- file jalan sebagai owner (root) untuk semua user"),
	mk(`\b(?:usermod|gpasswd|adduser|useradd)\b[^|;&]{0,120}`+
		`(?:^|[^\w-])(?:sudo|wheel|admin|root)(?:[^\w-]|$)`,
		"bagi keahlian group setara root"),
	mk(`NOPASSWD`, "bagi sudo tanpa password"),
	mk(`>\|?>?\s{0,4}/etc/sudoers\.d/|\btee\b[^|;]{0,120}/etc/sudoers`, "pasang rule sudo baru"),
	mk(`\bsudo\b[^|;&]{0,200}\b(?:find|tar|zip|awk|gawk|mawk|perl|python\d?|ruby`+
		`|node|lua|vim|vi|view|nano|ed|less|more|man|ftp|nmap|git|env|nice`+
		`|tcpdump|rsync|xargs)\b[^|;&]{0,200}`+
		`(?:/bin/(?:ba|z|k|da)?sh|\bsystem\s*\(|\bos\.system|pty\.spawn`+
		`|\bexec\s*\(|:!|!\s{0,2}/bin/|--interactive|checkpoint-action=exec)`,
		"living off the land: sudo jalankan tool yang lepas tu buka root shell"),

	// persistence.
	mk(`(?:^|[^>])>\|?\s{0,4}\S{0,64}`+shellRC+`(?:$|[^\w.])`,
		"tindih fail startup shell, buang semua yang dah ada dalam tu"),

	// history and log tampering.
	mk(`(?:^|[^>])>\|?\s{0,4}\S{0,64}\.(?:bash|zsh|sh)_history`+
		`|\b(?:rm|shred|truncate)\b[^|;]{0,120}\.(?:bash|zsh|sh)_history`+
		`|\bunset\s+HISTFILE(?:$|[^\w])|\bHISTFILE=(?:/dev/null|\s|$)`+
		`|\bset\s\+o\s+history\b|\bexport\s+HISTSIZE=0\b`,
		"padam atau matikan history shell -- sorok apa yang dijalankan"),
	mk(`(?:^|[^>])>\|?\s{0,4}/var/log/\S+`+
		`|\btruncate\b[^|;]{0,80}-s\s{0,2}0\s+/var/log/`+
		`|\bjournalctl\b[^|;]{0,80}--vacuum-(?:time|size|files)`,
		"kosongkan log sistem di tempat"),

	// firewall / MAC controls.
	mk(`\bufw\b[^|;&]{0,60}\b(?:disable|reset)\b|\bsetenforce\s+0\b`+
		`|\bsystemctl\b[^|;&]{0,60}\b(?:stop|disable|mask)\b[^|;&]{0,60}`+
		`\b(?:firewalld|ufw|iptables|nftables|apparmor)\b`+
		`|\biptables\b[^|;&]{0,80}-P\s+(?:INPUT|FORWARD)\s+DROP\b`,
		"matikan firewall host atau mandatory access control dia"),

	// storage teardown addressed by NAME.
	mk(`\b(?:lvremove|vgremove|pvremove)\b|\bzpool\s+destroy\b|\bzfs\s+destroy\b`+
		`|\bmdadm\b[^|;]{0,80}--zero-superblock\b`+
		`|\bhdparm\b[^|;]{0,80}--security-erase`,
		"musnah logical volume, pool atau array"),
	mk(`\bumount\b[^|;]{0,40}(?:-\w{0,3}a\s|-\w{0,3}a$|(?:^|\s)/(?:\s|$))`,
		"unmount root filesystem (atau semua sekali)"),

	// remote code execution beyond curl|sh.
	mk(`\b(?:curl|wget)\b[^|;]{0,200}\|\s{0,4}(?:sudo\s+)?`+
		`(?:python\d?(?:\.\d+)?|perl|ruby|node|php)\b`,
		"salurkan content internet terus ke interpreter"),
	mk(`(?:\b(?:ba|z|k|da)?sh\b|\bsource\b|(?:^|[^\w.])\.\s)[^|;]{0,40}`+
		`<\(\s{0,4}(?:curl|wget)\b`+
		`|\beval\b[^|;]{0,60}["']?\$\(\s{0,4}(?:curl|wget)\b`,
		"jalankan content remote guna process substitution -- sama macam curl | sh"),
	mk(`\bbase64\b[^|;]{0,60}(?:-d|--decode)[^|;]{0,60}`+
		`\|\s{0,4}(?:sudo\s+)?(?:ba|z|k|da)?sh\b`,
		"decode dan jalankan content yang disorok"),
}

// git clean needs two flag clusters (f-or-x AND d-or-x); handled apart because
// the Python rule used two lookaheads RE2 cannot express.
var gitCleanF = regexp.MustCompile(`\bgit\s+clean\b[^|;]*-\w*[fx]`)
var gitCleanD = regexp.MustCompile(`\bgit\s+clean\b[^|;]*-\w*[dx]`)

// authorized_keys: a truncating redirect, or a tee WITHOUT an append flag.
var akRedirect = regexp.MustCompile(`(?:^|[^>])>\|?\s*[^\s|;>]*authorized_keys`)
var akTee = regexp.MustCompile(`\btee\b[^|;]*authorized_keys`)
var akTeeAppend = regexp.MustCompile(`\btee\s+-\w*a`)

var wholeCaution = []rule{
	mk(`\brsync\b[^|;]*--delete\b`,
		"rsync --delete buang fail di destinasi yang tiada di source"),
	mk(`\b(awk|cut|sed)\b[^|]*\|\s*xargs\b[^|]*\b(kill|docker\s+rm|rm)\b`,
		"bunuh/buang guna field yang di-parse dari teks -- pastikan column tu betul-betul ID"),
	mk(`\b(?:fuser|pkill|killall|kill)\b(?:\s+-{1,2}\w+)*\s+-?\d+\s*(?:$|[|;&])`,
		"bunuh process ikut nombor port atau pid literal -- confirm betul ke tak"),
	mk(`\b(curl|wget)\b[^|;]*\b(https?://|[a-z0-9-]+\.[a-z]{2,})`, "hubungi network"),
	mk(`\bdocker\s+system\s+prune\b[^|;]*-a|\bdocker\s+system\s+prune\s+-a`,
		"buang semua docker image tak guna, bukan dangling je"),
	mk(`\bsudo\b`, "perlu sudo"),
	mk(`\bsetfacl\b[^|;]*-\w*R\w*[^|;]*(?:^|\s)`+
		`(/|/etc|/usr|/var|/home|/boot|/bin|/sbin|/root)(?:\s|$)`,
		"tulis semula ACL secara rekursif atas laluan kritikal"),

	// semantic classes, at CAUTION.
	mk(`\b(?:cat|less|more|head|tail|strings|xxd|od|base64)\b`+
		`[^|;]{0,200}(?:`+secretFile+`)`,
		"papar private key atau fail credential ke terminal"),
	mk(`/dev/(?:tcp|udp)/`, "buka raw network socket melalui /dev/tcp bash"),
	mk(`\|\s{0,4}(?:sudo\s+)?crontab\s+-\s{0,4}(?:$|[|;&])`,
		"`crontab -` ganti SELURUH crontab dengan apa yang dibaca"),
	mk(`>>\s{0,4}\S{0,64}`+shellRC+`(?:$|[^\w.])`+
		`|\btee\b[^|;]{0,120}`+shellRC+`(?:$|[^\w.])`+
		`|(?:>\|?>?|\btee\b[^|;]{0,120})\s{0,4}`+
		`/etc/(?:cron\.[a-z]{1,8}/|crontab|rc\.local|systemd/system/|init\.d/)`,
		"pasang code yang jalan sendiri setiap kali login atau boot"),
	mk(`\bchmod\b[^|;]{0,120}\s(?:[0-7]?[0-7]{2}[2367](?:\s|$)|[ugoa]*o\+w)`,
		"buat file boleh ditulis oleh semua user dalam mesin"),
	mk(`\bchmod\b[^|;]{0,120}\s(?:0?2[0-7]{3}(?:\s|$)|[ugoa]*g\+s)`, "set bit setgid"),
	mk(`\bmount\b[^|;]{0,80}\bremount\b[^|;]{0,40}(?:^|\s)/(?:\s|$)`,
		"remount root filesystem -- service yang tengah jalan mungkin mula gagal"),
}

// ping without a -c count runs forever; two Python lookaheads, handled apart.
var pingRe = regexp.MustCompile(`^\s*(sudo\s+)?ping\b`)
var pingCountRe = regexp.MustCompile(`\s-[a-zA-Z]*c\b|\s-c\d`)

var placeholderRe = regexp.MustCompile(`<[^<>\s][^<>]*>`)
var placeholderHint = regexp.MustCompile(
	`(/path/to/|/path/of/|\byour[-_]|\bmy[-_]|\bfilename\b|\bscript_name\b|` +
		`\bcontainer[-_]id\b|example\.com|username/repo)`)

// findDeletes / findRepermissions / findNarrow key the find(1) branch.
var findDeletes = regexp.MustCompile(`-delete\b|-(?:exec|ok)\w*\s+(sudo\s+)?(rm|shred|truncate)\b`)
var findReperm = regexp.MustCompile(`-(?:exec|ok)\w*\s+(sudo\s+)?(chmod|chown|chgrp)\b`)
var findNarrow = regexp.MustCompile(
	`-i?(?:name|path|regex)\b|-(?:mtime|mmin|atime|amin|ctime|cmin|size|newer)\b`)
var findFilter = regexp.MustCompile(`-i?(?:name|path|regex)\b`)
var substHead = regexp.MustCompile(`\$\(|` + "`")
var devBlock = regexp.MustCompile(`/dev/(sd|nvme|hd|vd|mmcblk)`)
var writeSystemDir = regexp.MustCompile(`(^|\s)(>|>>)\|?\s*/(etc|usr|var|boot|lib|sbin|bin)/`)

// splitSegments splits on shell operators so each clause is judged on its own.
// A lone `|` is a pipe, but `>|` is bash's force-clobber redirect (one token),
// so a `|` immediately after `>` is kept.
func splitSegments(command string) []string {
	var segs []string
	var cur strings.Builder
	flush := func() {
		if s := strings.TrimSpace(cur.String()); s != "" {
			segs = append(segs, s)
		}
		cur.Reset()
	}
	for i := 0; i < len(command); {
		c := command[i]
		switch c {
		case ';', '\n':
			flush()
			i++
		case '&':
			flush()
			if i+1 < len(command) && command[i+1] == '&' {
				i += 2
			} else {
				i++
			}
		case '|':
			if i+1 < len(command) && command[i+1] == '|' {
				flush()
				i += 2
			} else if i > 0 && command[i-1] == '>' {
				cur.WriteByte(c) // >| force-clobber, not a pipe
				i++
			} else {
				flush()
				i++
			}
		default:
			cur.WriteByte(c)
			i++
		}
	}
	flush()
	return segs
}

// Check returns the findings for a command. An empty slice means nothing
// flagged. Reasons are colloquial Malay; the caller renders the banner.
func Check(command string) []Finding {
	if strings.TrimSpace(command) == "" {
		return nil
	}
	clean := stripControl(command)
	// Placeholders are documentation, not shell syntax: the `>` inside
	// `docker exec -it <container-id> sh` must not read as a redirect.
	scan := placeholderRe.ReplaceAllString(clean, "PLACEHOLDER")

	var findings []Finding
	for _, r := range wholeDanger {
		if r.re.MatchString(scan) {
			findings = append(findings, Finding{LevelDanger, r.reason})
		}
	}
	if gitCleanF.MatchString(scan) && gitCleanD.MatchString(scan) {
		findings = append(findings, Finding{LevelDanger,
			"git clean padam fail untracked tanpa boleh recover"})
	}
	if akRedirect.MatchString(scan) ||
		(akTee.MatchString(scan) && !akTeeAppend.MatchString(scan)) {
		findings = append(findings, Finding{LevelDanger,
			"tindih authorized_keys -- boleh kunci kau keluar dari ssh"})
	}
	for _, r := range wholeCaution {
		if r.re.MatchString(scan) {
			findings = append(findings, Finding{LevelCaution, r.reason})
		}
	}
	if pingRe.MatchString(scan) && !pingCountRe.MatchString(scan) {
		findings = append(findings, Finding{LevelCaution,
			"ping tanpa -c akan jalan sampai kau interrupt"})
	}

	// Stateful cd tracking (see the Python comments for each guard).
	cwdIsCritical := false
	cwdAscended := false
	cdSeen := false

	for _, seg := range splitSegments(scan) {
		toks := tokenize(seg)
		if len(toks) == 0 {
			continue
		}

		// Strip no-op wrappers and VAR=value prefixes, then basename the binary.
		for len(toks) > 0 {
			head := toks[0]
			if strings.Contains(head, "=") && !strings.HasPrefix(head, "-") &&
				!strings.HasPrefix(head, "/") && isIdentifier(head[:strings.Index(head, "=")]) {
				toks = toks[1:]
				continue
			}
			base := head[strings.LastIndex(head, "/")+1:]
			if wrappers[base] {
				toks = toks[1:]
				valueOpts := wrapperValueOpts[base]
				for len(toks) > 0 && toks[0] != "--" && strings.HasPrefix(toks[0], "-") {
					opt := toks[0]
					toks = toks[1:]
					if valueOpts[opt] && len(toks) > 0 && !strings.HasPrefix(toks[0], "-") {
						toks = toks[1:]
					}
				}
				if len(toks) > 0 && toks[0] == "--" {
					toks = toks[1:]
				}
				continue
			}
			break
		}
		if len(toks) == 0 {
			continue
		}

		// A command name from substitution cannot be resolved statically.
		if substHead.MatchString(toks[0]) {
			findings = append(findings, Finding{LevelCaution,
				"nama command datang dari substitution -- tak boleh sahkan apa yang akan jalan"})
			continue
		}

		verb := toks[0][strings.LastIndex(toks[0], "/")+1:]

		// `bash -c "<command>"` hides the command inside a string argument.
		if shellRunners[verb] {
			for i := 1; i < len(toks); i++ {
				if toks[i] == "-c" && i+1 < len(toks) {
					findings = append(findings, Check(toks[i+1])...)
					break
				}
			}
		}

		// `eval STRING` is the other run-this-text form.
		if verb == "eval" && len(toks) > 1 {
			findings = append(findings, Check(strings.Join(toks[1:], " "))...)
			continue
		}

		args := toks[1:]
		flags := flagLetters(toks)

		if verb == "rsync" && hasDeleteFlag(args) {
			positional := positionals(args)
			if len(positional) > 0 {
				if crit, why := isCritical(positional[len(positional)-1]); crit {
					findings = append(findings, Finding{LevelDanger,
						"rsync --delete ke laluan kritikal: " + why})
				}
			}
		}

		if verb == "cd" {
			target := firstPositional(args)
			if target != "" {
				crit, _ := isCritical(target)
				cwdIsCritical = crit
				if containsSeg(target, "..") {
					cwdAscended = true
				} else if strings.HasPrefix(target, "/") {
					cwdAscended = false // absolute cd re-anchors
				}
			}
			cdSeen = true
			continue
		}

		switch {
		case destructiveVerbs[verb]:
			hit := false
			for _, a := range args {
				if crit, why := isCritical(a); crit {
					findings = append(findings, Finding{LevelDanger, verb + ": " + why})
					hit = true
					break
				}
			}
			if !hit && cwdIsCritical && anyGlob(args) {
				findings = append(findings, Finding{LevelDanger,
					verb + ": glob dalam directory kritikal yang dimasuki oleh cd sebelum ni"})
				hit = true
			}
			if !hit && cwdAscended && anyGlob(args) {
				findings = append(findings, Finding{LevelDanger, verb +
					": glob delete dalam directory yang dicapai guna 'cd ..' -- target ialah " +
					"parent tempat kau mula, yang ini tak boleh resolve"})
				hit = true
			}
			if !hit && !cdSeen && (flags["r"] || flags["R"]) {
				positional := positionals(args)
				if len(positional) > 0 && allWholeCwd(positional) {
					findings = append(findings, Finding{LevelDanger, verb +
						": recursive delete current directory (tak diketahui -- takde cd sebelum ni) " +
						"tanpa subdirectory atau nama filter untuk hadkan"})
					hit = true
				}
			}
			if !hit {
				for _, a := range args {
					if !strings.HasPrefix(a, "-") &&
						(placeholderRe.FindString(a) == a || placeholderHint.MatchString(a)) {
						findings = append(findings, Finding{LevelDanger, verb +
							": target ialah placeholder -- laluan sebenar yang kau letak akan " +
							"dipadam kekal"})
						break
					}
				}
			}
		case verb == "find":
			deletes := findDeletes.MatchString(seg)
			reperm := findReperm.MatchString(seg)
			if deletes || reperm {
				label := "find + chmod/chown"
				if deletes {
					label = "find + delete"
				}
				var roots []string
				for _, a := range args {
					if strings.HasPrefix(a, "-") {
						break
					}
					roots = append(roots, a)
				}
				hit := false
				narrowed := findNarrow.MatchString(seg)
				for _, a := range roots {
					if crit, why := isCritical(a); crit {
						lvl := LevelDanger
						if narrowed && normPath(a) != "/" {
							lvl = LevelCaution
						}
						findings = append(findings, Finding{lvl, label + ": " + why})
						hit = true
						break
					}
				}
				if !hit && !cdSeen && deletes {
					rootIsCwd := len(roots) == 0
					if !rootIsCwd {
						rootIsCwd = true
						for _, r := range roots {
							if r != "." && r != "./" {
								rootIsCwd = false
								break
							}
						}
					}
					if rootIsCwd && !findFilter.MatchString(seg) {
						findings = append(findings, Finding{LevelDanger,
							"find + delete: recursive delete bawah current directory tanpa " +
								"nama/path filter untuk hadkan"})
					}
				}
			}
		case moveVerbs[verb]:
			if verb == "mv" && len(args) > 0 {
				if crit, why := isCritical(args[0]); crit {
					findings = append(findings, Finding{LevelDanger, "mv: " + why})
				}
			}
		case permVerbs[verb]:
			positional := positionals(args)
			recursive := flags["r"] || flags["R"]
			for _, a := range rest(positional) {
				crit, why := isCritical(a)
				if crit && !recursive && strings.Contains(why, "variable tak di-expand") {
					continue
				}
				if crit {
					suffix := ""
					if recursive {
						suffix = " -R"
					}
					findings = append(findings, Finding{LevelDanger, verb + suffix + ": " + why})
					break
				}
			}
		case verb == "ln":
			if flags["f"] && len(args) > 0 {
				if crit, why := isCritical(args[len(args)-1]); crit {
					findings = append(findings, Finding{LevelDanger,
						"ln -f: " + why + " (diganti oleh link baru)"})
				}
			}
		case verb == "install":
			if len(args) > 0 {
				if crit, why := isCritical(args[len(args)-1]); crit {
					findings = append(findings, Finding{LevelDanger, "install: " + why})
				}
			}
		case verb == "wipefs" || verb == "blkdiscard" || verb == "sgdisk":
			for _, a := range args {
				if devBlock.MatchString(a) {
					findings = append(findings, Finding{LevelDanger, verb + ": wipe block device"})
					break
				}
			}
		case verb == "tee":
			for _, a := range args {
				if crit, why := isCritical(a); crit {
					findings = append(findings, Finding{LevelDanger,
						"tee: " + why + " (ditulis oleh tee)"})
					break
				}
			}
		case verb == "dd":
			for _, a := range args {
				if strings.HasPrefix(a, "of=") {
					if crit, why := isCritical(a[3:]); crit {
						findings = append(findings, Finding{LevelDanger,
							"dd: " + why + " (ditindih oleh dd)"})
					}
					break
				}
			}
		}

		if writeSystemDir.MatchString(seg) {
			findings = append(findings, Finding{LevelCaution, "tulis ke directory sistem"})
		}
	}

	if placeholderRe.MatchString(clean) || placeholderHint.MatchString(clean) {
		findings = append(findings, Finding{LevelCaution,
			"ada placeholder -- ganti dulu sebelum jalankan"})
	}

	return dedup(findings)
}

// --- small helpers ----------------------------------------------------------

func isIdentifier(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') {
			continue
		}
		if i > 0 && r >= '0' && r <= '9' {
			continue
		}
		return false
	}
	return true
}

func hasDeleteFlag(args []string) bool {
	for _, a := range args {
		if a == "--delete" || strings.HasPrefix(a, "--delete") {
			return true
		}
	}
	return false
}

func positionals(args []string) []string {
	var out []string
	for _, a := range args {
		if !strings.HasPrefix(a, "-") {
			out = append(out, a)
		}
	}
	return out
}

func firstPositional(args []string) string {
	for _, a := range args {
		if !strings.HasPrefix(a, "-") {
			return a
		}
	}
	return ""
}

func rest(s []string) []string {
	if len(s) <= 1 {
		return nil
	}
	return s[1:]
}

func containsSeg(path, seg string) bool {
	for _, p := range strings.Split(path, "/") {
		if p == seg {
			return true
		}
	}
	return false
}

func anyGlob(args []string) bool {
	for _, a := range args {
		if !strings.HasPrefix(a, "-") && strings.ContainsAny(a, "*?[") {
			return true
		}
	}
	return false
}

func allWholeCwd(positional []string) bool {
	for _, p := range positional {
		switch p {
		case "*", ".", "./", "./*":
		default:
			return false
		}
	}
	return true
}

func dedup(findings []Finding) []Finding {
	seen := map[Finding]bool{}
	var out []Finding
	for _, f := range findings {
		if !seen[f] {
			seen[f] = true
			out = append(out, f)
		}
	}
	return out
}
